export const Menuitem=[
    {
        title:"HOME",
        url:"/",
        cName:"nav-links"
    },
    {
        title:"VIDEOS",
        url:"/videos",
        cName:"nav-links"
    },
    {
        title:"BLOG",
        url:"/blog",
        cName:"nav-links"
    },
    {
        title:"STORE",
        url:"/store",
        cName:"nav-links"
    },
    {
        title:"ABOUT",
        url:"/about",
        cName:"nav-links"
    },
    {
        title:"CONTACT",
        url:"/contact",
        cName:"nav-links"
    }

]